### ISSUE TITLE
Is there a way to generate the flowchart via CLI?

### ISSUE THREAD

**Issue by platform-kit** [sugia/codeflow#1]
see title

**Comment by sugia** [comment]
Hello, generating a flowchart via CLI is not supported at the moment, though this feature is included in our Business Suite API roadmap. For now, you can generate a flowchart by visiting [https://codeflow.jomimi.com/graph](https://codeflow.jomimi.com/graph), where you can upload a file or a folder directly.

**Comment by platform-kit** [comment]
Obviously there are many cases where sharing a codebase with an external API is an instant no-go.

Bummer.
